### ISSUE TITLE
ttn_app missing

### ISSUE THREAD

**Issue by nottheedge** [TheThingsArchive/nodered-app-node#60]
Hi,

I installed nodered using docker on my RPI3b+. I tried to install nodered-contrib-ttn which gives also success message, but for some reasons ttn_app is missing. Therefore I can't connect to the network with my nodes. 

I also removed the container for nodered and installed newly. Same result.

Do you have any advise how to solve that issue?

![nr-contrib-ttn](https://user-images.githubusercontent.com/13378792/63517978-517f4080-c4f0-11e9-9930-713b41f723b0.PNG)

I'm running Nodered v0.20.7 and npm v5.03

Thanks in advance.

**Comment by johanstokking** [comment]
Is this the same as #44 or #59 ?

**Comment by johanstokking** [comment]
RPi support is now deprecated. We'll add guides for V3 to work with builtin Node-RED nodes (i.e. the MQTT input and output nodes)
